const JOB_SOURCES = [
  {
    id: 'linkedin',
    name: 'LinkedIn',
    icon: '💼',
    color: '#0077b5',
    bg: '#e8f4fd',
    url: 'https://www.linkedin.com/jobs/',
    searchUrl: 'https://www.linkedin.com/jobs/search/?keywords=',
    desc: 'Platform profesional terbesar. Cocok untuk networking dan melamar posisi korporat, startup, hingga MNC.',
    tags: ['Profesional', 'Networking', 'MNC', 'Startup'],
    rating: 5,
    tips: 'Aktifkan "Open to Work" dan optimalkan profil dengan keyword yang relevan.'
  },
  {
    id: 'jobstreet',
    name: 'Jobstreet',
    icon: '🔍',
    color: '#e8192c',
    bg: '#fde8ea',
    url: 'https://www.jobstreet.co.id/',
    searchUrl: 'https://www.jobstreet.co.id/id/jobs?q=',
    desc: 'Platform lowongan terbesar di Asia Tenggara. Banyak perusahaan lokal dan multinasional.',
    tags: ['Lokal', 'ASEAN', 'Fresh Graduate', 'Experienced'],
    rating: 5,
    tips: 'Set job alert agar notifikasi lowongan baru langsung masuk ke email.'
  },
  {
    id: 'talentics',
    name: 'Talentics',
    icon: '🎯',
    color: '#6c47ff',
    bg: '#ede9fe',
    url: 'https://talentics.id/',
    searchUrl: 'https://talentics.id/jobs?q=',
    desc: 'Platform rekrutmen berbasis AI untuk perusahaan teknologi dan startup Indonesia.',
    tags: ['Tech', 'Startup', 'AI-Matched', 'Indonesia'],
    rating: 4,
    tips: 'Lengkapi skill assessment untuk meningkatkan visibilitas profil kamu.'
  },
  {
    id: 'glints',
    name: 'Glints',
    icon: '✨',
    color: '#f97316',
    bg: '#fff7ed',
    url: 'https://glints.com/id',
    searchUrl: 'https://glints.com/id/opportunities/jobs/explore?keyword=',
    desc: 'Platform karir untuk generasi muda Asia. Banyak lowongan startup dan perusahaan digital.',
    tags: ['Young Professional', 'Startup', 'Digital', 'Remote'],
    rating: 4,
    tips: 'Ikuti komunitas dan event virtual untuk memperluas network.'
  },
  {
    id: 'kalibrr',
    name: 'Kalibrr',
    icon: '🚀',
    color: '#10b981',
    bg: '#d1fae5',
    url: 'https://www.kalibrr.id/',
    searchUrl: 'https://www.kalibrr.id/id-ID/job-board#q=',
    desc: 'Platform rekrutmen dengan sistem matching berbasis skill dan kepribadian.',
    tags: ['Skill-based', 'Fresh Graduate', 'Lokal', 'Matching'],
    rating: 4,
    tips: 'Selesaikan tes kepribadian dan skill untuk mendapat rekomendasi yang lebih akurat.'
  },
  {
    id: 'indeed',
    name: 'Indeed',
    icon: '🌐',
    color: '#003a9b',
    bg: '#e8eeff',
    url: 'https://id.indeed.com/',
    searchUrl: 'https://id.indeed.com/jobs?q=',
    desc: 'Mesin pencari lowongan global terbesar. Mengagregasi lowongan dari berbagai sumber.',
    tags: ['Global', 'Aggregator', 'Remote', 'Semua Level'],
    rating: 4,
    tips: 'Gunakan filter "Remote" untuk menemukan pekerjaan work from home.'
  },
  {
    id: 'techinasia',
    name: 'Tech in Asia Jobs',
    icon: '💻',
    color: '#e91e63',
    bg: '#fce4ec',
    url: 'https://www.techinasia.com/jobs',
    searchUrl: 'https://www.techinasia.com/jobs?search[keywords]=',
    desc: 'Platform khusus untuk industri teknologi dan startup di Asia.',
    tags: ['Tech', 'Startup', 'Asia', 'Engineering'],
    rating: 4,
    tips: 'Cocok untuk posisi engineering, product, dan growth di startup tech.'
  },
  {
    id: 'karir',
    name: 'Karir.com',
    icon: '📋',
    color: '#0ea5e9',
    bg: '#e0f2fe',
    url: 'https://www.karir.com/',
    searchUrl: 'https://www.karir.com/search/jobs?q=',
    desc: 'Platform lokal Indonesia dengan ribuan lowongan dari perusahaan terpercaya.',
    tags: ['Lokal', 'Indonesia', 'Terpercaya', 'Semua Industri'],
    rating: 3,
    tips: 'Aktifkan fitur "Lamar Cepat" untuk mempercepat proses aplikasi.'
  },
  {
    id: 'jobplanet',
    name: 'Jobplanet',
    icon: '🌍',
    color: '#8b5cf6',
    bg: '#ede9fe',
    url: 'https://www.jobplanet.co.id/',
    searchUrl: 'https://www.jobplanet.co.id/jobs?q=',
    desc: 'Platform dengan review perusahaan dari karyawan. Bisa cek kultur perusahaan sebelum melamar.',
    tags: ['Review', 'Kultur', 'Salary Info', 'Indonesia'],
    rating: 4,
    tips: 'Baca review perusahaan untuk mengetahui kultur kerja sebelum melamar.'
  },
  {
    id: 'urbanhire',
    name: 'Urbanhire',
    icon: '🏙️',
    color: '#f59e0b',
    bg: '#fef3c7',
    url: 'https://urbanhire.com/',
    searchUrl: 'https://urbanhire.com/jobs?q=',
    desc: 'Platform rekrutmen modern untuk perusahaan Indonesia dengan fitur ATS terintegrasi.',
    tags: ['Modern', 'ATS', 'Indonesia', 'Corporate'],
    rating: 3,
    tips: 'Pastikan CV kamu ATS-friendly agar lolos seleksi otomatis.'
  },
  {
    id: 'remote',
    name: 'Remote.co',
    icon: '🏠',
    color: '#059669',
    bg: '#d1fae5',
    url: 'https://remote.co/remote-jobs/',
    searchUrl: 'https://remote.co/remote-jobs/search/?search_keywords=',
    desc: 'Khusus lowongan remote/WFH dari seluruh dunia. Ideal untuk digital nomad.',
    tags: ['Remote', 'WFH', 'Global', 'Flexible'],
    rating: 4,
    tips: 'Siapkan portofolio online yang kuat karena persaingan bersifat global.'
  },
  {
    id: 'freelancer',
    name: 'Freelancer.com',
    icon: '🎨',
    color: '#1dbf73',
    bg: '#d1fae5',
    url: 'https://www.freelancer.com/',
    searchUrl: 'https://www.freelancer.com/jobs/?q=',
    desc: 'Platform freelance global untuk proyek jangka pendek maupun panjang.',
    tags: ['Freelance', 'Project', 'Global', 'Flexible'],
    rating: 3,
    tips: 'Bangun reputasi dengan mengambil proyek kecil terlebih dahulu.'
  }
];

const STATUS_LIST = ['Applied', 'Test', 'Interview', 'Offer', 'Rejected', 'Ghosted'];

const SAMPLE_APPLICATIONS = [
  { id: 1, company: 'Tokopedia', position: 'Frontend Developer', source: 'linkedin', status: 'Interview', date: '2025-01-10', salary: '15-20jt', location: 'Jakarta', notes: 'Interview HR sudah selesai, menunggu technical interview', url: 'https://linkedin.com', priority: 'High' },
  { id: 2, company: 'Gojek', position: 'Software Engineer', source: 'glints', status: 'Applied', date: '2025-01-12', salary: '18-25jt', location: 'Jakarta', notes: 'Menunggu respon dari HR', url: '', priority: 'High' },
  { id: 3, company: 'Traveloka', position: 'React Developer', source: 'jobstreet', status: 'Test', date: '2025-01-08', salary: '12-18jt', location: 'Jakarta', notes: 'Online test dijadwalkan 20 Januari', url: '', priority: 'Medium' },
  { id: 4, company: 'Bukalapak', position: 'Full Stack Dev', source: 'kalibrr', status: 'Rejected', date: '2025-01-05', salary: '10-15jt', location: 'Bandung', notes: 'Tidak lolos seleksi CV', url: '', priority: 'Low' },
  { id: 5, company: 'Shopee', position: 'UI Engineer', source: 'linkedin', status: 'Offer', date: '2025-01-03', salary: '20-28jt', location: 'Jakarta', notes: 'Offer diterima! Menunggu kontrak', url: '', priority: 'High' },
  { id: 6, company: 'Grab', position: 'Mobile Developer', source: 'talentics', status: 'Ghosted', date: '2024-12-28', salary: '15-22jt', location: 'Jakarta', notes: 'Sudah 3 minggu tidak ada kabar', url: '', priority: 'Medium' },
];
